#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : olefile
Version  : 0.46
Release  : 26
URL      : https://files.pythonhosted.org/packages/34/81/e1ac43c6b45b4c5f8d9352396a14144bba52c8fec72a80f425f6a4d653ad/olefile-0.46.zip
Source0  : https://files.pythonhosted.org/packages/34/81/e1ac43c6b45b4c5f8d9352396a14144bba52c8fec72a80f425f6a4d653ad/olefile-0.46.zip
Summary  : Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office)
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: olefile-python3
Requires: olefile-license
Requires: olefile-python
BuildRequires : buildreq-distutils3

%description
=======
        
        |Build Status TravisCI| |Build Status AppVeyor| |Coverage Status|
        |Documentation Status| |PyPI| |Can I Use Python 3?| |Say Thanks!|

%package doc
Summary: doc components for the olefile package.
Group: Documentation

%description doc
doc components for the olefile package.


%package license
Summary: license components for the olefile package.
Group: Default

%description license
license components for the olefile package.


%package python
Summary: python components for the olefile package.
Group: Default
Requires: olefile-python3

%description python
python components for the olefile package.


%package python3
Summary: python3 components for the olefile package.
Group: Default
Requires: python3-core

%description python3
python3 components for the olefile package.


%prep
%setup -q -n olefile-0.46

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536633327
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/olefile
cp LICENSE.txt %{buildroot}/usr/share/doc/olefile/LICENSE.txt
cp doc/License.rst %{buildroot}/usr/share/doc/olefile/doc_License.rst
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/olefile/*

%files license
%defattr(-,root,root,-)
/usr/share/doc/olefile/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
