#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : olefile
Version  : 0.45.1
Release  : 15
URL      : http://pypi.debian.net/olefile/olefile-0.45.1.zip
Source0  : http://pypi.debian.net/olefile/olefile-0.45.1.zip
Summary  : Python package to parse, read and write Microsoft OLE2 files (Structured Storage or Compound Document, Microsoft Office) - Improved version of the OleFileIO module from PIL, the Python Image Library.
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: olefile-python3
Requires: olefile-python
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools

%description
=======
        
        |Build Status TravisCI| |Build Status AppVeyor| |Coverage Status|
        |Documentation Status| |PyPI| |Can I Use Python 3?|

%package python
Summary: python components for the olefile package.
Group: Default
Requires: olefile-python3

%description python
python components for the olefile package.


%package python3
Summary: python3 components for the olefile package.
Group: Default
Requires: python3-core

%description python3
python3 components for the olefile package.


%prep
%setup -q -n olefile-0.45.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523566812
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
